services:
  pug:
    image: node:lts-alpine
    container_name: spring-workshop-builder
    volumes:
      - .:/usr/app/
    working_dir: /usr/app
    command: /bin/ash -c "yarn && yarn run gulp pug copy"

  watch:
    image: node:lts-alpine
    volumes:
      - .:/usr/app/
    working_dir: /usr/app
    command: /bin/ash -c "yarn && yarn run gulp watch"

  web:
    image: nginx:alpine
    container_name: workshop-net-ict-e-titech-ac-jp
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html
    ports:
      - "8080:80"
    command: /bin/ash -c "exec nginx -g 'daemon off;'"
    networks:
      - spring-workshop

networks:
  spring-workshop:
