version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
     - "8080:80"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
