# https://taskfile.dev

version: 3

silent: true

tasks:
  default:
    cmds:
      - mkdir -p public/
      - docker compose up pug
      - docker compose up -d web
      - docker compose logs -f web
  build:
    cmds:
      - mkdir -p public/
      - docker compose up --force-recreate pug
      - task _web
      - echo -e "\U26A1 \e[33mCheck out http://localhost:8080"
  _web:
    cmds:
      - docker compose up --force-recreate -d web
  clean:
    cmds:
      - docker compose down
      - rm -rf public/
