# See: https://github.com/marketplace/actions/github-action-for-yarn
# See: https://github.com/marketplace/actions/publish-docker

name: GitHub CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Generate HTML Files with Pug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run gulp build
  publish-docker:
    name: Build and Publish Docker Image to GitHub Package Registry
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: yamaoka-kitaguchi-lab/spring-workshop/spring-workshop-nginx
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          snapshot: true
          tags: "latest"

