# See: https://github.com/marketplace/actions/github-action-for-yarn
# See: https://github.com/marketplace/actions/publish-docker

name: GitHub CI/CD

on:
  push:
    branches: [master]
    paths:
      - ".github/**"
      - "spring-workshop/**"
      - "Dockerfile"
      - "gulpfile.js"
      - "nginx.conf"
      - "yarn.lock"
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Generate HTML Files with Pug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install
      - run: yarn run gulp build
      - uses: actions/upload-artifact@v3
        if: github.event_name != 'pull_request'
        with:
          name: pug-build-artifacts
          path: public

  publish-docker:
    name: Build and Publish Docker Image to GitHub Package Registry
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/download-artifact@v3
        with:
          name: pug-build-artifacts
          path: public
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: yamaoka-kitaguchi-lab/spring-workshop/spring-workshop-nginx
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          snapshot: true
          tags: "latest"
